# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NEWUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(411, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 60, 311, 391))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, 20, 10, 20)
        self.gridLayout_2.setSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ConnectButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ConnectButton.setFont(font)
        self.ConnectButton.setObjectName("ConnectButton")
        self.gridLayout_2.addWidget(self.ConnectButton, 1, 0, 1, 1)
        self.ClearBridgeButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ClearBridgeButton.setFont(font)
        self.ClearBridgeButton.setObjectName("ClearBridgeButton")
        self.gridLayout_2.addWidget(self.ClearBridgeButton, 1, 1, 1, 1)
        self.QuitButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.QuitButton.setFont(font)
        self.QuitButton.setObjectName("QuitButton")
        self.gridLayout_2.addWidget(self.QuitButton, 2, 0, 1, 1)
        self.ClearAllVolt = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ClearAllVolt.setFont(font)
        self.ClearAllVolt.setObjectName("ClearAllVolt")
        self.gridLayout_2.addWidget(self.ClearAllVolt, 2, 1, 1, 1)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 20, 10, 14)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(14)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 7, 1, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 7, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 2, 0, 1, 1)
        self.Regulator1 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Regulator1.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.Regulator1.setFont(font)
        self.Regulator1.setObjectName("Regulator1")
        self.gridLayout.addWidget(self.Regulator1, 2, 2, 1, 1)
        self.Regulator2 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Regulator2.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.Regulator2.setFont(font)
        self.Regulator2.setObjectName("Regulator2")
        self.gridLayout.addWidget(self.Regulator2, 7, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(180, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ChannelClose = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ChannelClose.setFont(font)
        self.ChannelClose.setObjectName("ChannelClose")
        self.gridLayout_3.addWidget(self.ChannelClose, 1, 0, 1, 1)
        self.ChannelOpen = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ChannelOpen.setFont(font)
        self.ChannelOpen.setObjectName("ChannelOpen")
        self.gridLayout_3.addWidget(self.ChannelOpen, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(50, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.gridLayout_3)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 411, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.ClearBridgeButton.setText(_translate("MainWindow", "ClearBridgeVolt"))
        self.QuitButton.setText(_translate("MainWindow", "Quit"))
        self.ClearAllVolt.setText(_translate("MainWindow", "ClearAllVolt"))
        self.label_2.setText(_translate("MainWindow", "  Value"))
        self.label_3.setText(_translate("MainWindow", "     Input V"))
        self.Regulator1.setText(_translate("MainWindow", "Regulator 1"))
        self.Regulator2.setText(_translate("MainWindow", "Regulator 2"))
        self.label_4.setText(_translate("MainWindow", "  Make Changes"))
        self.ChannelClose.setText(_translate("MainWindow", "Channel Close"))
        self.ChannelOpen.setText(_translate("MainWindow", "Channel Open"))
        self.label_5.setText(_translate("MainWindow", "  NO"))
        self.label.setText(_translate("MainWindow", "                  Controller"))
